create database Dhamo_bharotta;
use dhamo_bharotta;
set foreign_key_checks=0;
create table regions(region_id int unsigned not null primary key, region_name varchar(30));
insert into regions(region_id, region_name) values(1, 'Europe');
create table countries(country_id char not null primary key, country_name varchar(30), region_id int unsigned not null);
create table locations(location_id int unsigned not null auto_increment primary key, street_address varchar(60), postal_code varchar(6), city varchar(20) not null, state_provience varchar(30), country_id char not null);
insert into locations(location_id, street_address, postal_code, city, state_provience, country_id) values(1200,'2017 shinjuku-ku','1689','tokyo','tokyo prefecture','j');
create table departments(department_id int unsigned not null primary key, department_name varchar(30) not null, manager_id int unsigned, location_id int unsigned);
insert into departments(department_id,department_name,manager_id,location_id) values(10,'administration',200,1700);
create table jobs(job_id varchar(50) not null primary key, job_title varchar(30) not null, min_salary decimal unsigned, max_salary decimal unsigned);
insert into jobs(job_id,job_title,min_salary,max_salary) values('ad_vp','administration vice president',15000,30000);
create table employees(employee_id int unsigned not null primary key, first_name varchar(30), last_name varchar(30) not null, email varchar(50) not null, phone_number varchar(30), hire_date date not null, job_id varchar(40) not null, salary decimal not null, comission_pct decimal, manager_id int unsigned, department_id int unsigned);
insert into employees(employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,comission_pct,manager_id,department_id) values(100,'steven','king','sking','515.123.4567',date '1987-06-17','ad_pes',24000,null,null,90);
create table job_histories(employee_id int unsigned not null, start_date date not null, end_date date not null, job_id varchar(50) not null, department_id int unsigned not null);
insert into job_histories(employee_id,start_date,end_date,job_id,department_id) values(200,date '1987-08-17',date '1993-06-17','ad_asst',90);
alter table countries add constraint FK_regioncountry foreign key(region_id) references regions(region_id);
alter table locations add constraint FK_countrylocation foreign key(country_id) references countries(country_id);
alter table job_histories drop primary key, add primary key(employee_id,start_date);
alter table departments drop primary key, add primary key(department_id, manager_id);
alter table employees add foreign key(job_id) references jobs(job_id), add foreign key(department_id,manager_id) references departments(department_id,manager_id);
alter table locations add foreign key(country_id) references countries(country_id);
alter table departments add foreign key(location_id) references locations(location_id);
select * from locations;
desc locations;
select * from departments;
desc departments;
select* from countries;
desc countries;
select * from regions;
desc regions;
select * from jobs;
desc jobs;
select * from job_histories;
desc job_histories;
select * from employees;
desc employees;